### ISSUE TITLE
Regarding the input size of ppg

### ISSUE THREAD

**Issue by tawichi** [Nikitha-ramasetti/BP_Estimation_PPG#1]
Hi.
Thanks for the very informative information. 
I have one question about your code  of cnn-lstm.py.
What is the input size of the PPG?

Thanks.

**Comment by Nikitha-ramasetti** [comment]
Hello,

Sorry, for the delayed response.

As the sampling rate of the Physiologic waveform records - PPG and ABP
signals are *125 Hz* (125 samples per second) recorded.
The input size of PPG was *3750 samples* (30-second window frame taken) (*30
*125*).


Best Regards,
Nikitha Ramasetti
